controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
users_delete:
  path: /administration/user/user/{id}/delete
  methods: ['POST']
  controller: App\Controller\UserController::delete

users_confirm:
  path: /administration/user/user/{id}/confirm
  methods: ['POST']
  controller: App\Controller\UserController::confirm